- name: Working with variables
  hosts: node12 
  vars:
    port_nums: [21,22,23,25,80,443]
    
    users:
      bob:
        username: bob
        uid: 1122
        shell: /bin/bash
      lisa: 
        username: lisa
        uid: 2233
        shell: /bin/sh
  tasks:
    - name: show me 2nd item in port_nums
      debug:
        msg: Shell port  is {{ port_nums[1] }}
    - name: show the uid of bob
      debug: 
        msg: UID of bob is {{ users.bob.uid }}
